### ISSUE TITLE
No Issue, But how to Use the MIB to Data Model Conversion

### ISSUE THREAD

**Issue by mgarcia01752** [BroadbandForum/cwmp-xml-tools#5]
How can I take a SNMP MIB and convert it to a Data Model?

**Comment by wlupton** [comment]
Please take a look at the [MIB Conversion Tool](https://github.com/BroadbandForum/cwmp-xml-tools/tree/master/MIB_Conversion_Tool) (in this repository).

**Comment by mgarcia01752** [comment]
Do I need to use the smidump utility to convert SNMP MIB to MIB-XML? I

**Comment by wlupton** [comment]
Yes. See the makefile for examples of which options to use.

**Comment by wlupton** [comment]
Note that this should produce a valid data model but it will be a literal translation of the MIB, i.e. will still be in the MIB world. Depending on your requirements you may then need to hand-edit it.
