### ISSUE TITLE
Tr069 not saving configuration after reboot

### ISSUE THREAD

**Issue by sunitha1970** [BroadbandForum/cwmp-xml-tools#9]
Hi,
I have set the wan parameters like vlan,username, password through ACS server. The vlan ,username and password are reflecting in onu.But when onu is rebooted the changes disappear.. it will go to default configuration.

**Comment by sunitha1970** [comment]
All the configuration including tr069, SSID are changing to default

**Comment by sunitha1970** [comment]
Can someone help me to to solve this issue

**Comment by wlupton** [comment]
Hello. It sounds like this question relates to a particular implementation of a CWMP Agent. Is that correct? If so, I think you need to contact the implementer!
